---
name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go:
          - 1.16.x
          - tip

    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        if: ${{ matrix.go != 'tip' }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Setup Go tip
        if: ${{ matrix.go == 'tip' }}
        run: |
          which -a go
          go env

      - name: Install tools
        run: make init

      - name: Test with race detector
        run: make race

      - name: Gather test coverage
        run: make cover

      - name: Upload test coverage report to coveralls.io
        uses: shogo82148/actions-goveralls@v1.4.3
        with:
          path-to-profile: profile.cov
