---
name: Go

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        go: [1.16.x]
        may-fail: [false]
        include:
          - go: tip
            may-fail: true

    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.may-fail }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go v${{ matrix.go }}
        if: ${{ matrix.go != 'tip' }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Go tip
        if: ${{ matrix.go == 'tip' }}
        run: |
          curl -OL https://github.com/AlekSi/golang-tip/releases/download/tip/master.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf master.linux-amd64.tar.gz
          sudo ln -vsf /usr/local/go/bin/* /usr/bin/
          sudo ln -vsf /usr/local/go/bin/* /bin/

      - name: Run debug commands
        run: |
          env
          which -a go
          go version
          go env

      - name: Install tools
        run: make init

      - name: Test with race detector
        run: make race

      - name: Gather test coverage
        run: make cover

      - name: Upload test coverage report to coveralls.io
        uses: shogo82148/actions-goveralls@v1.6.0
        with:
          path-to-profile: profile.cov
