name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Init
      run: make init

    - name: Race
      run: make race

    - name: Cover
      run: make cover
      
    - name: Bench
      run: make bench

    - name: Goveralls
      uses: shogo82148/actions-goveralls@v1.4.3
      with:
        path-to-profile: profile.cov

